version: '3.8'

services:
  app:
    image: local/zookeeper-demo
    build:
      context: .
      target: dev
    command: sh -c "dockerize -wait tcp://zoo1:2181 -timeout 300s -wait-retry-interval 5s python subscriber.py"
    depends_on:
      - zoo1
      - zoo2
    volumes:
      - .:/app  
  zoo1:
    image: zookeeper
    hostname: zoo1
    # ports:
    #   - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181
  zoo2:
    image: zookeeper
    hostname: zoo2
    # ports:
    #   - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181
